// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://meczgsrnjogdhbqhkoud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lY3pnc3Juam9nZGhicWhrb3VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM2OTI5NjQsImV4cCI6MjA0OTI2ODk2NH0.WkipTqg10-lruGfRffBes8JOYuP7ztAwsE3Exq7xvvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);